# Configuração do golangci-lint para o MSC Shard Router
# Versão simplificada para evitar problemas de compatibilidade

run:
  timeout: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - tmp

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/msfidelis/msc-transactions-api
  
  govet:
    enable-all: false
    enable:
      - assign
      - atomic
      - bools
      - copylocks
      - httpresponse
      - printf
      - tests
  
  errcheck:
    check-type-assertions: false
    check-blank: false
  
  gosec:
    excludes:
      - G404

linters:
  enable:
    - errcheck
    - typecheck
    - unused
    - gofmt
    - goimports


  disable-all: true  # Só habilita os linters específicos acima

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
    
    - path: main\.go
      linters:
        - errcheck

  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: error